#UTP Artificial Intelligence

##### Egy Vedriyanto
2117051035

Dataset yang digunakan https://github.com/vineethvs23/Anime-Recommendation/blob/master/anime.csv

Dataset RAW https://raw.githubusercontent.com/vineethvs23/Anime-Recommendation/master/anime.csv

##Library

In [ ]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

##Dataset

In [ ]:
data = pd.read_csv("https://raw.githubusercontent.com/vineethvs23/Anime-Recommendation/master/anime.csv")
data

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

##Preprocessing

In [ ]:
#Supaya terhindar dari kesesatan kita hapus data yang hanya bergenre Hentai:)
data = data[data["genre"] != "Hentai"]
data

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12272,18197,Nudl Nude,"Comedy, Hentai, Parody",OVA,1,4.14,186
12273,18199,Nudl Nude 2,"Comedy, Hentai, Parody",OVA,1,4.00,146
12277,12397,Original Video Romance Animation,"Comedy, Hentai",OVA,2,4.66,176
12278,17833,Pink no Curtain,"Hentai, Slice of Life",OVA,1,3.61,138
12285,34399,Taimanin Asagi 3,"Demons, Hentai, Supernatural",OVA,Unknown,NaN,485

In [ ]:
#menghapus data yang memiliki nilai Null / NaN
data.dropna(inplace=True)
data

<ipython-input-22-f83ed7de32bf>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.dropna(inplace=True)

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12268,23677,Manga Edo Erobanashi,"Comedy, Hentai, Historical",OVA,5,2.86,111
12272,18197,Nudl Nude,"Comedy, Hentai, Parody",OVA,1,4.14,186
12273,18199,Nudl Nude 2,"Comedy, Hentai, Parody",OVA,1,4.00,146
12277,12397,Original Video Romance Animation,"Comedy, Hentai",OVA,2,4.66,176
12278,17833,Pink no Curtain,"Hentai, Slice of Life",OVA,1,3.61,138

In [ ]:
#Mengganti kolom type menjadi data float
data['type'] = data['type'].replace('ONA', 'OVA')
data['type'] = data['type'].replace('Movie', 0)
data['type'] = data['type'].replace('TV', 1)
data['type'] = data['type'].replace('OVA', 2)
data['type'] = data['type'].replace('Special', 3)
data['type'] = data['type'].replace('Music', 4)
data['type'] = data['type'].astype(float)

#Mengganti episode yang Unknown menjadi 1 
data['episodes'] = data['episodes'].replace('Unknown', 1)
data

<ipython-input-23-5d80435b92fb>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['type'] = data['type'].replace('ONA', 'OVA')
<ipython-input-23-5d80435b92fb>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['type'] = data['type'].replace('Movie', 0)
<ipython-input-23-5d80435b92fb>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['type'] = data['type'].replace('TV', 1)
<ipython-input-23-5d80435b92fb>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['type'] = data['type'].replace('OVA', 2)
<ipython-input-23-5d80435b92fb>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['type'] = data['type'].replace('Special', 3)
<ipython-input-23-5d80435b92fb>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['type'] = data['type'].replace('Music', 4)
<ipython-input-23-5d80435b92fb>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['type'] = data['type'].astype(float)
<ipython-input-23-5d80435b92fb>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['episodes'] = data['episodes'].replace('Unknown', 1)

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",0.0,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",1.0,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",1.0,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",1.0,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",1.0,51,9.16,151266
...,...,...,...,...,...,...,...
12268,23677,Manga Edo Erobanashi,"Comedy, Hentai, Historical",2.0,5,2.86,111
12272,18197,Nudl Nude,"Comedy, Hentai, Parody",2.0,1,4.14,186
12273,18199,Nudl Nude 2,"Comedy, Hentai, Parody",2.0,1,4.00,146
12277,12397,Original Video Romance Animation,"Comedy, Hentai",2.0,2,4.66,176
12278,17833,Pink no Curtain,"Hentai, Slice of Life",2.0,1,3.61,138

In [ ]:
#Untuk data training kita buat duplikat agar data hanya berisi angka
data_train = data.drop(['name', 'genre'], axis=1)
data_train

       anime_id  type episodes  rating  members
0         32281   0.0        1    9.37   200630
1          5114   1.0       64    9.26   793665
2         28977   1.0       51    9.25   114262
3          9253   1.0       24    9.17   673572
4          9969   1.0       51    9.16   151266
...         ...   ...      ...     ...      ...
12268     23677   2.0        5    2.86      111
12272     18197   2.0        1    4.14      186
12273     18199   2.0        1    4.00      146
12277     12397   2.0        2    4.66      176
12278     17833   2.0        1    3.61      138

[11201 rows x 5 columns]

In [ ]:
#Memisahkan fitur dengan target
X = data_train.drop("type", axis=1)
y = data_train["type"]

In [ ]:
#Splitting data
#Karena data lebih dari 800 maka menggunakan rasio 4:1
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

##Modeling

In [ ]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [ ]:
#prediksi data test
y_pred = model.predict(X_test)

In [ ]:
#menghitung akurasi
accuracy = accuracy_score(y_test, y_pred)
print("Akurasi model:", accuracy*100, "%")

Akurasi model: 60.776439089692104 %

##Evaluasi Model

In [ ]:
#menambah metode random forest
model = RandomForestClassifier(n_estimators=100, random_state=0)

In [ ]:
model.fit(X_train, y_train)

RandomForestClassifier(random_state=0)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
#Akurasi baru setelah menggunakan RandomForest
accuracy = accuracy_score(y_test, y_pred)
print("Akurasi :", accuracy*100, "%")

Akurasi : 70.45961624274877 %

##Evaluasi model menggunakan data dummy baru

In [ ]:
# membuat data dummy baru
dummy = {'Nama Anime': ['Fullmetal Alchemist', 'Death Note', 'Black Clover', 'Sword Art Online', 'Sailor Moon'],
        'Action': [1, 1, 1, 1, 0],
        'Adventure': [1, 0, 1, 1, 0],
        'Fantasy': [0, 1, 0, 0, 1],
        'Comedy': [0, 1, 1, 0, 0]}

df = pd.DataFrame(dummy)
print(df)

            Nama Anime  Action  Adventure  Fantasy  Comedy
0  Fullmetal Alchemist       1          1        0       0
1           Death Note       1          0        1       1
2         Black Clover       1          1        0       1
3     Sword Art Online       1          1        0       0
4          Sailor Moon       0          0        1       0

In [ ]:
# Memisahkan kolom yang akan digunakan sebagai fitur (X) dan target (y)
X = df[['Adventure','Fantasy','Comedy']]
y = df['Action']

# Membagi data menjadi data latih dan data uji
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Melatih model dengan Logistic Regression
clf = LogisticRegression(max_iter=100)
clf.fit(X_train, y_train)

# Menguji model dengan data uji
y_pred = clf.predict(X_test)

In [ ]:
#menghitung akurasi
accuracy = accuracy_score(y_test, y_pred)
print("Akurasi model:", accuracy*100, "%")

Akurasi model: 100.0 %